.PHONY: clean All

All:
	@echo "----------Building project:[ helloworld - Debug ]----------"
	@$(MAKE) -f  "helloworld.mk"
clean:
	@echo "----------Cleaning project:[ helloworld - Debug ]----------"
	@$(MAKE) -f  "helloworld.mk" clean
