.PHONY: clean All

All:
	@echo "----------Building project:[ linklist - Debug ]----------"
	@cd "linklist" && $(MAKE) -f  "linklist.mk"
clean:
	@echo "----------Cleaning project:[ linklist - Debug ]----------"
	@cd "linklist" && $(MAKE) -f  "linklist.mk" clean
